spring.application.name=auth-service
server.port=8082

# MUST point to the exact same file path as Product Service
spring.datasource.url=jdbc:h2:file:../data/UrbanVogueDB;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
# In production, this should be a long, random string
jwt.secret=urbanvogue-super-secret-key-for-tokengeneration-2026-very-secure-key
# 72 hours (in milliseconds)
jwt.expiration=259200000