spring.application.name=payment-service
server.port=8084

# Same shared DB as all other services
spring.datasource.url=jdbc:h2:file:C:/Users/sarvamangala.b/Downloads/urban-vogue-parent/data/UrbanVogueDB;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Order Service URL ? Payment needs to update order status after payment
order.service.url=http://localhost:8083

# Payment simulation success rate (90% succeed)
payment.simulation.success-rate=0.9